### ISSUE TITLE
file opening problems

### ISSUE THREAD

**Issue by TheHexCoder0x10** [yoyoberenguer/BLOOM#5]
when I try to open any files after importing bloom effect it says that the file doesn't exist and gives the error
FileNotFoundError: No file 'Assets/GlitchGoblin-2O87v.ttf' found in working directory 'C:\Users\TheHe\PycharmProjects\Project55\venv310\lib\site-packages\BloomEffect\tests'.
thats just one example  it always says the working directory is that

**Comment by yoyoberenguer** [comment]
Hi, 
Did you install BloomEffect using pip? or from the Github source code ? 

`GlitchGoblin-2O87v.ttf ` file is not a file included in BloomEffect project.
This file a numeric font. Are you trying to bloom this file ? 

Can you share the lines of code that leads to that error message? or send a screenshot?

Kind regards

**Comment by TheHexCoder0x10** [comment]
it was a font file that i was just trying to open had nothing to do with bloom i was using it as an example and I installed using pip i fixed it by using this line os.chdir(os.environ['PYTHONPATH'])

**Comment by TheHexCoder0x10** [comment]
![image_2023-11-18_192910843](https://github.com/yoyoberenguer/BloomEffect/assets/119265202/68330ed9-b310-4e0a-b0e4-b2efac1f0078)
heres the line that was causing problems

**Comment by yoyoberenguer** [comment]
Glad you solved your issue, 
I will close this issue since this was external to the project BloomEffect 
Have a nice weekend 
Kind Regards
